name: drf-project

services:
  movies-db:
    image: postgres:15.2
    interfaces:
      main: 5432
  movies-srvc:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn drf_project.wsgi:application --bind 0.0.0.0:8000
    interfaces:
      main: 8000
    depends_on:
      - movies-db