databases:
  - name: movies-db

services:
  - type: web
    name: movies
    env: docker
    plan: individual
    dockerCommand: ./Dockerfile.prod
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        value: localhost 127.0.0.1 [::1]
      - key: DATABASE_URL
        fromDatabase:
          name: movies-db
          property: connectionString